/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */

package org.zowe.apiml.gateway.acceptance;

import org.apache.commons.lang3.StringUtils;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.zowe.apiml.gateway.acceptance.common.AcceptanceTestWithBasePath;
import org.zowe.apiml.gateway.acceptance.common.MicroservicesAcceptanceTest;

import static io.restassured.RestAssured.given;
import static org.apache.hc.core5.http.HttpStatus.SC_OK;
import static org.hamcrest.Matchers.is;

/**
 * In z/OS tokens can be large if generated by z/OSMF and the user has many groups
 */
@MicroservicesAcceptanceTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class RequestLimitTest extends AcceptanceTestWithBasePath {

    private static final String HEADER_10KB = StringUtils.repeat("1", 10_000);

    @Test
    void whenLargeRequestHeader_then200() {
        given()
            .header("X-BIG-HEADER-1", HEADER_10KB)
            .header("x-BIG-HEADER-2", HEADER_10KB)
            .header("x-BIG-HEADER-3", HEADER_10KB)
            .header("x-BIG-HEADER-4", HEADER_10KB)
        .when()
            .get(basePath + "/application/version")
        .then()
            .statusCode(is(SC_OK));

    }

}
