name: "Setup action"
description: "Prepares for execution - set up Java, Node, npm, Gradle"

inputs:
    jdkVersion:
        description: "JDK version"
        required: false
        default: "17"

runs:
    using: "composite"
    steps:
        -   name: Set up JDK ${{ inputs.jdkVersion }}
            uses: actions/setup-java@v4
            with:
                distribution: 'semeru'
                java-version: ${{ inputs.jdkVersion }}
        -   name: Set up Node
            uses: actions/setup-node@v4
            with:
                node-version: '20'
        -   run: npm install -g npm@10.7.0
            shell: bash
        -   name: Grant execute permission for gradlew
            run: chmod +x gradlew
            shell: bash

        -   name: Cache Gradle packages
            uses: actions/cache@v4
            with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle', 'settings.gradle', '*/build.gradle', '*/gradle/**/*.gradle', '*/gradle/**/*.properties') }}
        -   name: Cache Node.js modules of root folder
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    node_modules
                key: ${{ runner.OS }}-node-${{ hashFiles('*.json') }}
        -   name: Cache Node.js modules of API Catalog
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    api-catalog-ui/frontend/node_modules
                key: ${{ runner.OS }}-api-catalog-ui-node-${{ hashFiles('api-catalog-ui/frontend/*.json') }}
        -   name: Cache Node.js modules of Zowe CLI ID Federation Plugin
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    zowe-cli-id-federation-plugin/node_modules
                key: ${{ runner.OS }}-zowe-cli-id-federation-plugin-node-${{ hashFiles('zowe-cli-id-federation-plugin/*.json') }}
        -   name: Cache Node.js modules of Onboarding Enabler Nodejs
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    onboarding-enabler-nodejs/node_modules
                key: ${{ runner.OS }}-onboarding-enabler-nodejs-node-${{ hashFiles('onboarding-enabler-nodejs/*.json') }}
        -   name: Cache Node.js modules of Onboarding Enabler Nodejs Sample App
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    onboarding-enabler-nodejs-sample-app/node_modules
                key: ${{ runner.OS }}-onboarding-enabler-nodejs-sample-app-node-${{ hashFiles('onboarding-enabler-nodejs-sample-app/*.json') }}
        -   name: Cache Node.js modules of ZSS Sample Service
            uses: actions/cache@v4
            with:
                path: |
                    ~/.npm
                    zss-sample-service/node_modules
                key: ${{ runner.OS }}-zss-sample-service-node-${{ hashFiles('zss-sample-service/*.json') }}
