./gradlew runIntegrationTests \
  -Dcredentials.user=username \
  -Dcredentials.password=password \
  -Ddiscovery.host=usilca32.lvn.broadcom.net \
  -Ddiscovery.port=11911 \
  -Ddiscovery.scheme=https \
  -Ddiscovery.instances=1 \
  -Dgateway.instances=1 \
  -Dgateway.host=usilca32.lvn.broadcom.net \
  -Dgateway.port=11910 \
  -Dgateway.scheme=https \
  -DtlsConfiguration.keyAlias=apiml \
  -DtlsConfiguration.keyStore=/c/keystore/ca3x/apiml.keystore.p12 \
  -DtlsConfiguration.trustStore=/c/keystore/ca3x/apiml.truststore.p12 \
  -Dzosmf.host=usilca32.ca.com \
  -Dzosmf.port=1443 \
  -Dzosmf.serviceId=zosmfca32
