plugins {
    id 'java'
}

dependencies {
    implementation libs.picocli
    annotationProcessor libs.picocli.codegen

    implementation project(':zosmf-jwt-check')

    testImplementation libs.mockito.core
    testImplementation libs.hamcrest
}

compileJava {
    options.compilerArgs += ["-Aproject=${project.group}/${project.name}"]
}

jar {
    dependsOn ':zosmf-jwt-check:jar'
    manifest {
        attributes(
            'Main-Class': 'org.zowe.apiml.Analyser'
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
