{
 "title": "APIML - Metrics-Service - HTTP",
 "description": "Dashboard for displaying HTTP metrics within the metrics service",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "GATEWAY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "description": "Request rate to show relative changes in traffic",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "requestCount" }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Execution complete with no errors",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountSuccess" }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "description": "Execution threw an exception",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountFailure" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "Request rate within the cluster",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Error%",
   "type": "gauge",
   "description": "Error percentage for the last 10 seconds",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "errorPercentage" }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "stat",
   "description": "execution threw a HystrixBadRequestException",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountBadRequests" }
   ]
  },
  {
   "title": "Time out",
   "type": "stat",
   "description": "execution started, but did not complete in the allowed time\t",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountTimeout" }
   ]
  },
  {
   "title": "Short-Circuited",
   "type": "stat",
   "description": "circuit breaker OPEN, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountShortCircuited" }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "description": "thread pool at capacity, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "rollingCountThreadPoolRejected" }
   ]
  },
  {
   "title": "Hosts_Last 10 s",
   "type": "stat",
   "description": "Hosts reported in the last 10 seconds",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "reportingHostsLast10Seconds" }
   ]
  },
  {
   "title": "Hosts_Total",
   "type": "stat",
   "description": "Hosts reporting from cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "reportingHosts" }
   ]
  },
  {
   "title": "Circuit-Breaker Open?",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "isCircuitBreakerOpen" }
   ]
  },
  {
   "title": "Latency-Total-Mean",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "latencyTotal_mean" }
   ]
  },
  {
   "title": "Latency-Total-90th",
   "type": "stat",
   "description": "90th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "latencyTotal['90']" }
   ]
  },
  {
   "title": "Latency-Total-99th",
   "type": "stat",
   "description": "99th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "latencyTotal['99']" }
   ]
  },
  {
   "title": "Latency-Total-99.5th",
   "type": "stat",
   "description": "99.5th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "GATEWAY", "metricName": "latencyTotal['99.5']" }
   ]
  },
  { "title": "DISCOVERY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "description": "Request rate to show relative changes in traffic",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "requestCount" }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Execution complete with no errors",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountSuccess" }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "description": "Execution threw an exception",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountFailure" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "Request rate within the cluster",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 30 }
   ]
  },
  {
   "title": "Error%",
   "type": "gauge",
   "description": "Error percentage for the last 10 seconds",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "errorPercentage" }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "stat",
   "description": "execution threw a HystrixBadRequestException",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountBadRequests" }
   ]
  },
  {
   "title": "Time out",
   "type": "stat",
   "description": "execution started, but did not complete in the allowed time\t",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountTimeout" }
   ]
  },
  {
   "title": "Short-Circuited",
   "type": "stat",
   "description": "circuit breaker OPEN, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountShortCircuited" }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "description": "thread pool at capacity, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "rollingCountThreadPoolRejected" }
   ]
  },
  {
   "title": "Hosts_Last 10 s",
   "type": "stat",
   "description": "Hosts reported in the last 10 seconds",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "reportingHostsLast10Seconds" }
   ]
  },
  {
   "title": "Hosts_Total",
   "type": "stat",
   "description": "Hosts reporting from cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "reportingHosts" }
   ]
  },
  {
   "title": "Circuit-Breaker Open?",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "isCircuitBreakerOpen" }
   ]
  },
  {
   "title": "Latency-Total-Mean",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "latencyTotal_mean" }
   ]
  },
  {
   "title": "Latency-Total-90th",
   "type": "stat",
   "description": "90th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "latencyTotal['90']" }
   ]
  },
  {
   "title": "Latency-Total-99th",
   "type": "stat",
   "description": "99th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "latencyTotal['99']" }
   ]
  },
  {
   "title": "Latency-Total-99.5th",
   "type": "stat",
   "description": "99.5th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "DISCOVERY", "metricName": "latencyTotal['99.5']" }
   ]
  },
  { "title": "API CATALOG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Traffic Volume",
   "type": "timeseries",
   "description": "Request rate to show relative changes in traffic",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "requestCount" }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Execution complete with no errors",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountSuccess" }
   ]
  },
  {
   "title": "Failure",
   "type": "stat",
   "description": "Execution threw an exception",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountFailure" }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "description": "Request rate within the cluster",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 62 }
   ]
  },
  {
   "title": "Error%",
   "type": "gauge",
   "description": "Error percentage for the last 10 seconds",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "errorPercentage" }
   ]
  },
  {
   "title": "Bad Requests",
   "type": "stat",
   "description": "execution threw a HystrixBadRequestException",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountBadRequests" }
   ]
  },
  {
   "title": "Time out",
   "type": "stat",
   "description": "execution started, but did not complete in the allowed time\t",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountTimeout" }
   ]
  },
  {
   "title": "Short-Circuited",
   "type": "stat",
   "description": "circuit breaker OPEN, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountShortCircuited" }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "description": "thread pool at capacity, execution not attempted",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "rollingCountThreadPoolRejected" }
   ]
  },
  {
   "title": "Hosts_Last 10 s",
   "type": "stat",
   "description": "Hosts reported in the last 10 seconds",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "reportingHostsLast10Seconds" }
   ]
  },
  {
   "title": "Hosts_Total",
   "type": "stat",
   "description": "Hosts reporting from cluster",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "reportingHosts" }
   ]
  },
  {
   "title": "Circuit-Breaker Open?",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "isCircuitBreakerOpen" }
   ]
  },
  {
   "title": "Latency-Total-Mean",
   "type": "stat",
   "description": "Status of the Circuit breaker, true for open, false for closed",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "latencyTotal_mean" }
   ]
  },
  {
   "title": "Latency-Total-90th",
   "type": "stat",
   "description": "90th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "latencyTotal['90']" }
   ]
  },
  {
   "title": "Latency-Total-99th",
   "type": "stat",
   "description": "99th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "latencyTotal['99']" }
   ]
  },
  {
   "title": "Latency-Total-99.5th",
   "type": "stat",
   "description": "99.5th percentile of total latency",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "clusterName": "APICATALOG", "metricName": "latencyTotal['99.5']" }
   ]
  }
 ]
}