/*
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 */

package org.zowe.apiml.gradle.keystore;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.tasks.Internal;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Generates the TLS keystores needed to run the services locally and under test.
 *
 * <p>The generated test fixtures under zaas-client/src/test/resources and
 * common-service-core/src/test/resources are written by {@link KeystoreGenerator} too, but are
 * deliberately NOT declared as task outputs: that would make those source directories task outputs,
 * and every task that reads them — checkLicenseTest, processTestResources — would need an explicit
 * ordering. Licence checking has nothing to do with TLS material and must not wait on it.
 */
public abstract class GenerateKeystoresTask extends DefaultTask {

    /**
     * Files that must all be present for an existing tree to count as complete. Checking a
     * representative set rather than "any *.p12 exists" means a partial tree — an interrupted run,
     * an incomplete CI artifact — regenerates instead of being silently accepted.
     */
    private static final List<String> REQUIRED = List.of(
        "keystore/localhost/localhost.keystore.p12",
        "keystore/localhost/localhost.truststore.p12",
        "keystore/localhost/nonlocalhost.keystore.p12",
        "keystore/docker/all-services.keystore.p12",
        "keystore/client_cert/client-certs.p12",
        "zaas-client/src/test/resources/localhost.keystore.p12",
        "common-service-core/src/test/resources/jwt-public-key.pub"
    );

    private static final String STAMP = "keystore/generation.stamp";

    @OutputDirectory
    public abstract DirectoryProperty getKeystoreDirectory();

    /**
     * Internal rather than an input: this is the repository root, and treating it as an input would
     * have Gradle fingerprint the entire working tree on every build.
     */
    @Internal
    public abstract DirectoryProperty getRepoRoot();

    @TaskAction
    public void generate() throws Exception {
        new KeystoreGenerator(getRepoRoot().get().getAsFile().toPath()).generate();
    }

    /**
     * Whether the tree on disk is complete and was produced by the current generator.
     *
     * <p>Gradle's own up-to-date check cannot answer this: it needs execution history, which a fresh
     * clone and a CI job that unpacked a keystore artifact both lack. Without the stamp, a changed
     * generator would never regenerate anything on a developer machine that already has keystores.
     *
     * @return a human-readable reason to regenerate, or null when the tree can be left alone
     */
    public static String reasonToRegenerate(Path repoRoot) throws IOException {
        List<String> missing = REQUIRED.stream()
            .filter(path -> !Files.exists(repoRoot.resolve(path)))
            .toList();
        if (!missing.isEmpty()) {
            return "missing " + missing.size() + " of " + REQUIRED.size() + " expected files";
        }
        Path stamp = repoRoot.resolve(STAMP);
        if (!Files.exists(stamp)) {
            return "keystore/generation.stamp is absent";
        }
        String expected = String.valueOf(KeystoreGenerator.GENERATOR_VERSION);
        if (!expected.equals(Files.readString(stamp).trim())) {
            return "generated by a different revision of the keystore generator";
        }
        return null;
    }
}
