source.type=SOFT_INDEX_FILE_STORE
source.cache_name=invalidatedJwtTokens
source.location=caching-service/localhost/invalidatedJwtTokens/data
source.index_location=caching-service/localhost/invalidatedJwtTokens/index
source.version=15
#source.segment_count=256
#source.marshaller.class=org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller
#source.marshaller.allow-list.regexps=.*

target.type=SOFT_INDEX_FILE_STORE
#target.marshaller.class=org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller
#target.marshaller.allow-list.regexps=.*
target.cache_name=invalidatedJwtTokens
target.location=caching-service/localhost_NEW/invalidatedJwtTokens/data
target.index_location=caching-service/localhost_NEW/invalidatedJwtTokens/index
#target.segment_count=256
