@startuml
archimate #business "User" as user <<business-actor>>
archimate #application "API Client" as apiClient <<application-component>>
archimate #technology "Zowe API Gateway" as GW <<service>>
archimate #application "z/OSMF" as zosmf <<application-service>>
archimate #application "Zowe API Service" as zoweApiService <<application-service>>
archimate #application "z/OS API Service" as apiService <<application-service>>

apiClient --> GW: 1. logins and obtains Zowe JWT
apiClient --> GW: 2. provides Zowe JWT to API calls
user --> apiClient: provides credentials to API client
GW --> zoweApiService: provides Zowe JWT
GW --> apiService: provides PassTicket
GW --> zosmf: provides z/OSMF LTPA
@enduml
