buildscript {
    repositories mavenRepositories
    dependencies {
        classpath libs.spring.boot.gradle.plugin
        classpath libs.gradle.git.properties
        classpath libs.jgit
    }
}

plugins {
    alias(libs.plugins.gradle.git.properties)
}

group = 'org.zowe.apiml'
version = '3.1.13-SNAPSHOT'

apply plugin: 'org.springframework.boot'


dependencies {
    implementation libs.spring.boot.starter.web
    testImplementation libs.junit.jupiter
}

test {
    useJUnitPlatform()
}
