buildscript {
    repositories mavenRepositories
    dependencies {
        classpath libs.spring.boot.gradle.plugin
        classpath libs.jgit
    }
}

plugins {
    alias(libs.plugins.gradle.git.properties)
}

group = 'org.zowe.apiml'

apply plugin: 'org.springframework.boot'


dependencies {
    implementation(project(":gateway-service"))
    implementation(project(":discovery-service"))

    implementation(libs.bundles.modulith)
    implementation(libs.spring.boot.starter.web)
//    implementation(libs.spring.cloud.starter.eureka.server)

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)

    testCompileOnly(libs.lombok)
    testAnnotationProcessor(libs.lombok)

    testImplementation(libs.modulith.test)
    testImplementation(libs.junit.jupiter)
}

test {
    useJUnitPlatform()
}
