spring.profiles.active: debug,diag

eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30
    instance:
        leaseExpirationDurationInSeconds: 6
        leaseRenewalIntervalInSeconds: 1

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /service/server-only.p12
        keyStorePassword: password
        keyStoreType: PKCS12
        clientAuth: want
        trustStore: /service/service.truststore.p12
        trustStorePassword: password
        trustStoreType: PKCS12

apiml:
    service:
        ssl:
            key-store: /service/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /service/service.truststore.p12
            trust-store-password: password
        hostname: api-catalog-services
        port: 10014
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        gatewayHostname: https://gateway-service:10010
        preferIpAddress: false
    service-registry:
        cacheRefreshInitialDelayInMillis: 10000
        cacheRefreshRetryDelayInMillis: 10000
        cacheRefreshUpdateThresholdInMillis: 120000
        serviceFetchDelayInMillis: 10000
    banner: console
    discovery:
        staticApiDefinitionsDirectories: /api-defs;/docker/api-defs
    security:
        allowedDomains: discovery-service:*,discovery-service-2:*,discoverable-client:*,discoverable-client-2:*,api-catalog-services:*,api-catalog-services-2:*,caching-service:*,caching-service-2:*,caching-service-3:*,gateway-service:*,gateway-service-2:*,zaas-service:*,zaas-service-2:*,mock-services:*,mock-services-2:*,zowe.github.io,www.zowe.org,localhost:*,www.ibm.com,central-gateway-service:*,central-gateway-service-2:*,testrunner:*
spring:
    output:
        ansi:
            enabled: always

management:
    endpoints:
        web:
            exposure:
                include: "*"
