apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service
    security:
        x509:
            certificatesUrl: https://gateway-service:10010/gateway/certificates
server:
    ssl:
        keyAlias: localhost
        keyStore: /service/service.keystore.p12
        trustStore: /service/service.truststore.p12
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: debug
