apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        ssl:
            key-store: /service/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /service/service.truststore.p12
            trust-store-password: password

        hostname: caching-service
    banner: console
    security:
        x509:
            certificatesUrl: https://gateway-service:10010/gateway/certificates
server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyStore: /service/server-only.p12
        trustStore: /service/service.truststore.p12
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: debug

management:
    endpoints:
        web:
            exposure:
                include: "*"
