apiml:
    httpclient:
        ssl:
            key-store: /docker/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /docker/all-services.truststore.p12
            trust-store-password: password
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: caching-service
    banner: console

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyStore: /docker/server-only.p12
        trustStore: /docker/all-services.truststore.p12
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: debug
