apiml:
    service:
        hostname: cloud-gateway-service
eureka:
    client:
        serviceUrl:
            defaultZone: https://discovery-service:10011/eureka/
server:
    ssl:
        keyAlias: localhost
        keyStore: /service/service.keystore.p12
        trustStore: /service/service.truststore.p12
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: debug
