spring.profiles.include: diag
apiml:
    service:
        ssl:
            key-store: /service/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /service/service.truststore.p12
            trust-store-password: password
        hostname: discovery-service
    discovery:
        staticApiDefinitionsDirectories: /api-defs;/docker/api-defs
        allPeersUrls: https://discovery-service:10011/eureka
    security:
        allowedDomains: discovery-service,discovery-service-2,discoverable-client,discoverable-client-2,api-catalog-services,api-catalog-services-2,caching-service,caching-service-2,caching-service-3,gateway-service,gateway-service-2,zaas-service,zaas-service-2,mock-services,mock-services-2,zowe.github.io,www.zowe.org,localhost,www.ibm.com,central-gateway-service,central-gateway-service-2,testrunner
        ssl:
            verifySslCertificatesOfServices: true
    banner: console
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: diag

eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            access: unrestricted

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /service/server-only.p12
        keyStorePassword: password
        trustStore: /service/service.truststore.p12
        trustStorePassword: password
