spring.profiles.include: diag
apiml:
    service:
        ssl:
            key-store: /docker/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /docker/all-services.truststore.p12
            trust-store-password: password
        hostname: discovery-service
    discovery:
        staticApiDefinitionsDirectories: /api-defs;/docker/api-defs
        allPeersUrls: https://discovery-service:10011/eureka
    security:
        ssl:
            verifySslCertificatesOfServices: true
    banner: console
spring:
    output:
        ansi:
            enabled: always
    profiles:
        include: diag

eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            access: unrestricted

---
spring.config.activate.on-profile: https

server:
    address: 0.0.0.0
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /docker/server-only.p12
        keyStorePassword: password
        trustStore: /docker/all-services.truststore.p12
        trustStorePassword: password
