spring.profiles.include: diag,debug
apiml:
    service:
        ssl:
            key-store: /docker/client-cert.p12
            key-store-password: password
            key-password: password
            key-alias: localhost
            trust-store: /docker/all-services.truststore.p12
            trust-store-password: password
        apimlId: apiml1
        hostname: gateway-service
        discoveryServiceUrls: https://discovery-service:10011/eureka/
    banner: console
    security:
        allowedDomains: gateway-service,discovery-service,discoverable-client,api-catalog-services,caching-service,zaas-service,mock-services,zowe.github.io,www.zowe.org,localhost,www.ibm.com
eureka:
    client:
        instanceInfoReplicationIntervalSeconds: 30
        registryFetchIntervalSeconds: 30
spring:
    output:
        ansi:
            enabled: always

management:
    endpoints:
        migrate-legacy-ids: true
        web:
            exposure:
                include: "*"
    endpoint:
        shutdown:
            access: unrestricted

server:
    address: 0.0.0.0
    max-http-request-header-size: 40000
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStore: /docker/server-only.p12
        keyStorePassword: password
        trustStore: /docker/all-services.truststore.p12
        trustStorePassword: password
