apiml:
    service:
        discoveryServiceUrls: https://discovery-service:10011/eureka/
        hostname: metrics-service
        customMetadata:
            apiml:
                enableUrlEncodedCharacters: true
                corsAllowedOrigins: https://metrics-service:10019
                corsAllowedMethods: GET,POST,OPTIONS,HEAD
                corsAllowedHeaders: Content-Type,Authorization
                corsAllowCredentials: true

server:
    ssl:
        keyAlias: localhost
        keyStore: /service/service.keystore.p12
        trustStore: /service/service.truststore.p12
