export const FETCH_TILES_REQUEST = 'FETCH_TILES_REQUEST';

export const FETCH_TILES_STOP = 'FETCH_TILES_STOP';

export const FETCH_TILES_RETRY = 'FETCH_TILES_RETRY';

export const FETCH_TILES_SUCCESS = 'FETCH_TILES_SUCCESS';

export const FETCH_TILES_FAILED = 'FETCH_TILES_FAILED';

export const TILE_BY_ID = 'TILE_BY_ID';
