spring.profiles.active: debug,diag

logbackServiceName: ZWEAGW2
logging:
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS,UTC} %clr<${logbackServiceName}:%thread:${PID:}> %magenta(%X{userid:-}) %cyan(%-5level) %clr(\(%logger{15}\)) %msg%n'
    level:
        org.springframework.web.socket.client.standard.AnnotatedEndpointConnectionManager: DEBUG
        org.springframework.web.reactive.socket.client.StandardWebSocketClient: TRACE

server:
    max-http-request-header-size: 16348
    webSocket:
        requestBufferSize: 16348

eureka:
    server:
        myUrl: https://localhost:10021/eureka/
apiml:
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
        allPeersUrls: https://localhost:10011/eureka/
    internal-discovery:
        port: 10021
    health:
        protected: false
    gateway:
        registry:
            enabled: true
        servicesToLimitRequestRate: discoverableclient
        cookieNameForRateLimiter: apimlAuthenticationToken
    service:
        apimlId: apiml2

        discoveryServiceUrls: https://localhost:10021/eureka/
        forwardClientCertEnabled: false
        hostname: localhost
        id: ${spring.application.name}
        ignoredHeadersWhenCorsEnabled: Access-Control-Request-Method,Access-Control-Request-Headers,Access-Control-Allow-Origin,Access-Control-Allow-Methods,Access-Control-Allow-Headers,Access-Control-Allow-Credentials,Origin
        port: 10020
        externalUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}
        title: API ML 2
    security:
        x509:
            enabled: true
            certificatesUrl: https://localhost:10010/gateway/certificates
        allowTokenRefresh: true
        webfinger:
            fileLocation: config/local/webfinger.yml
        personalAccessToken:
            enabled: true
        oidc:
            enabled: false
            clientId:
            clientSecret:
            registry: zowe.okta.com
            identityMapperUrl: ${apiml.service.scheme}://${apiml.service.hostname}:${apiml.service.port}/zss/api/v1/certificate/dn
            identityMapperUser: APIMTST
            jwks:
                uri:
        auth:
            jwt:
                customAuthHeader: customJwtHeader
            passticket:
                customUserHeader: customUserHeader
                customAuthHeader: customPassticketHeader
            provider: zosmf
            zosmf:
                serviceId: mockzosmf  # Replace me with the correct z/OSMF service id
        useDummyCNMapper: true
        allowedDomains: localhost,localhost2,www.ibm.com,zowe.github.io,www.zowe.org
caching:
    storage:
        mode: infinispan
        infinispan:
            initialHosts: localhost[7600]

jgroups:
    bind:
        port: 7601
        address: localhost

management:
    endpoints:
        web:
            exposure:
                include: "*"
