spring.profiles.active: debug,diag

jgroups:
    bind:
        port: 7099
        address: localhost
caching:
    storage:
        mode: infinispan
        infinispan:
            persistence:
                dataLocation: data_replica
            initialHosts: localhost[7600]
apiml:
    service:
        port: 10022
    banner: console
    security:
        x509:
            certificatesUrl: https://localhost:10010/gateway/certificates

management:
    endpoints:
        web:
            exposure:
                include: "*"

logbackServiceName: ZWEACS2

logging:
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS,UTC} <%blue(${logbackServiceName}):%magenta(%thread):${PID:}> %X{userid:-} %clr(%-5level) %cyan(\(%logger{15}\)) %msg%n'
