spring.profiles.active: debug,diag

apiml:
    service:
        port: 10025
    banner: console
    security:
        x509:
            certificatesUrl: https://localhost:10010/gateway/certificates
jgroups:
    bind:
        port: 7600
        address: localhost
caching:
    storage:
        mode: infinispan
        infinispan:
            initialHosts: localhost[7099]

management:
    endpoints:
        web:
            exposure:
                include: "*"


logging:
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS,UTC} <%blue(${logbackServiceName}):%magenta(%thread):${PID:}> %X{userid:-} %clr(%-5level) %cyan(\(%logger{15}\)) %msg%n'
