jgroups:
    bind:
        port: 7099
        address: localhost
caching:
    storage:
        mode: infinispan
        infinispan:
            persistence:
                dataLocation: data_replica
            initialHosts: localhost[7600]
apiml:
    service:
        port: 10022
    banner: console
    security:
        x509:
            certificatesUrl: https://localhost:10010/gateway/certificates
spring:
    profiles:
        include: dev

management:
    endpoints:
        web:
            exposure:
                include: "*"
