jgroups:
    bind:
        port: 7098
        address: localhost
caching:
    storage:
        mode: vsam
        infinispan:
            initialHosts: localhost[7099]
spring:
    profiles:
        include: dev
