spring.profiles.include: diag

apiml:
    service:
        hostname: localhost
        ipAddress: 127.0.0.1
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
    security:
        ssl:
            verifySslCertificatesOfServices: true
        allowedDomains: localhost,localhost2,www.zowe.org,zowe.github.io,www.ibm.com
    banner: console
    metrics:
        enabled: true
spring:
    config:
        useLegacyProcessing: true
    output:
        ansi:
            enabled: always

eureka:
    client:
        initialInstanceInfoReplicationIntervalSeconds: 1
        registryFetchIntervalSeconds: 1

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/service/service.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/service/service.truststore.p12
        trustStorePassword: password

