spring.profiles.active: https,debug,diag

eureka:
    instance:
        ipAddress: 127.0.0.1

apiml:
    health.protected: true
    service:
        hostname: localhost
        port: 10011
    discovery:
        staticApiDefinitionsDirectories: config/local/api-defs
    security:
        allowedDomains: localhost,localhost2,www.ibm.com,zowe.github.io,www.zowe.org
        ssl.verifySslCertificatesOfServices: true
    banner: console

spring.output.ansi.enabled: always

management:
    endpoints:
        web:
            exposure:
                include: "*"

logging:
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS,UTC} <%blue(${logbackServiceName}):%magenta(%thread):${PID:}> %X{userid:-} %clr(%-5level) %cyan(\(%logger{15}\)) %msg%n'

server:
    ssl:
        keyAlias: localhost
        keyPassword: password
        keyStoreType: PKCS12
        keyStore: keystore/service/service.keystore.p12
        keyStorePassword: password
        trustStoreType: PKCS12
        trustStore: keystore/service/service.truststore.p12
        trustStorePassword: password
