source.type=SOFT_INDEX_FILE_STORE
source.cache_name=zoweInvalidatedTokenCache
source.location=caching-service/localhost/zoweInvalidatedTokenCache/data
source.index_location=caching-service/localhost/zoweInvalidatedTokenCache/index
source.version=15
#source.segment_count=256
#source.marshaller.class=org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller
#source.marshaller.allow-list.regexps=.*

target.type=SOFT_INDEX_FILE_STORE
#target.marshaller.class=org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller
#target.marshaller.allow-list.regexps=.*
target.cache_name=zoweInvalidatedTokenCache
target.location=caching-service/localhost_NEW/zoweInvalidatedTokenCache/data
target.index_location=caching-service/localhost_NEW/zoweInvalidatedTokenCache/index
#target.segment_count=256
