const userConstants = {
    USERS_LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    USERS_LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    USERS_LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',

    USERS_LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    USERS_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    USERS_LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',

};

export default userConstants;
