[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zowe-apiml-onboarding-enabler-python"
version = "3.0.0"
description = "Python enabler for Zowe API Mediation Layer"
authors = [{name = "Zowe Project"}]
license = {text = "EPL-2.0"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "pyyaml"
]

[tool.setuptools]
packages = {find = {where = "src"}}
