x-common-settings: &default-settings
    cap_drop:
        - NET_RAW

services:
    api-catalog-services:
        image: ghcr.io/zowe/api-catalog-services:latest
        <<: *default-settings
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs

    api-catalog-services-2:
        image: ghcr.io/zowe/api-catalog-services:latest
        <<: *default-settings
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs
        environment:
            - APIML_SERVICE_HOSTNAME=api-catalog-services-2

    caching-service:
        image: ghcr.io/zowe/caching-service:latest
        <<: *default-settings

    discoverable-client:
        image: ghcr.io/zowe/discoverable-client:latest
        <<: *default-settings

    discoverable-client-2:
        image: ghcr.io/zowe/discoverable-client:latest
        <<: *default-settings
        environment:
            - APIML_SERVICE_HOSTNAME=discoverable-client-2

    discovery-service:
        image: ghcr.io/zowe/discovery-service:latest
        <<: *default-settings
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs
        ports:
            - "10011:10011"
        environment:
            - APIML_DISCOVERY_ALLPEERSURLS=https://discovery-service:10011/eureka,https://discovery-service-2:10011/eureka

    discovery-service-2:
        image: ghcr.io/zowe/discovery-service:latest
        <<: *default-settings
        volumes:
            - ../../config/docker/api-defs-shared:/api-defs
        environment:
            - APIML_DISCOVERY_ALLPEERSURLS=https://discovery-service:10011/eureka,https://discovery-service-2:10011/eureka
            - APIML_SERVICE_HOSTNAME=discovery-service-2

    gateway-service:
        image: ghcr.io/zowe/gateway-service:latest
        <<: *default-settings
        ports:
            - "10010:10010"
        environment:
            - APIML_SERVICE_DISCOVERYSERVICEURLS=https://discovery-service:10011/eureka/,https://discovery-service-2:10011/eureka/

    gateway-service-2:
        image: ghcr.io/zowe/gateway-service:latest
        <<: *default-settings
        environment:
            - APIML_SERVICE_HOSTNAME=gateway-service-2
            - SERVER_INTERNAL_PORT=10027
            - APIML_SERVICE_DISCOVERYSERVICEURLS=https://discovery-service:10011/eureka/,https://discovery-service-2:10011/eureka/

    mock-services:
        image: ghcr.io/zowe/mock-services:latest
        <<: *default-settings
