dependencies {
    api project(':apiml-security-common')

    implementation libs.spring.boot.starter.security
    implementation libs.spring.cloud.starter.eureka.client
    implementation libs.spring.boot.jackson2

    implementation libs.apache.commons.lang3

    testImplementation libs.spring.boot.starter.test
    testImplementation(testFixtures(project(":apiml-common")))
    testImplementation(testFixtures(project(":apiml-security-common")))

    compileOnly libs.lombok
    testCompileOnly libs.lombok
    annotationProcessor libs.lombok
}
