# This workflow will release project with Gradle
name: Automated publish of nodejs and python enabler

on:
    workflow_dispatch:
        inputs:
            scope:
                description: 'Specify scope that is to be used.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major
                default: 'patch'
            version:
                description: 'Set version to override value in package.json in case of existing version in npm registry. Use the latest version in npm registry so the release plugin will properly increase from the current version.'
                required: false
                type: string
            enablerType:
                description: 'Specify which enabler to release.'
                type: choice
                required: false
                options:
                    - node
                    - python
                default: node

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        if: inputs.enablerType == 'node'

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

            - uses: ./.github/actions/setup

            - name: Clean git
              run: git reset --hard HEAD

            - name: Set email
              run: git config user.email "zowe-robot@users.noreply.github.com"

            - name: Set name
              run: git config user.name "Zowe Robot"

            - name: Update version manually
              if: github.event.inputs.version != ''
              run: |
                  cd onboarding-enabler-nodejs
                  sed -i.bak "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json
              env:
                  NEW_VERSION: ${{ github.event.inputs.version }}

            - name: Release to NPM automatic
              shell: bash
              run: |
                  cd onboarding-enabler-nodejs
                  echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                  npm version ${{ github.event.inputs.scope || env.DEFAULT_SCOPE }}
                  npm publish --access public
                  git add package.json
                  git add package-lock.json
                  git commit -m "[skip ci] Update version"
                  git push --no-verify
                  cd ..
              env:
                  DEFAULT_SCOPE: 'patch'
                  NPM_TOKEN: ${{ secrets.NPM_PUBLIC_TOKEN }}

            -  uses: ./.github/actions/teardown

    release-python-enabler:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        needs: release
        if: inputs.enablerType == 'python'

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14"

            - name: Install Dependencies
              run: |
                  cd onboarding-enabler-python
                  python -m venv venv
                  source venv/bin/activate
                  python -m pip install --upgrade pip setuptools wheel twine build
                  if [ -f Pipfile.lock ]; then
                    pip install pipenv
                    pipenv install --deploy --ignore-pipfile
                  fi

            - name: Build Python Package
              run: |
                  export SETUPTOOLS_SCM_PRETEND_VERSION=${{ github.event.inputs.version }}
                  ./gradlew onboarding-enabler-python:buildPython

            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheels
                  path: onboarding-enabler-python/dist/

            - name: Install twine globally
              run: python3 -m pip install --upgrade twine

            - uses: zowe-actions/octorelease@v1
              env:
                  GIT_COMMITTER_NAME: ${{ secrets.ZOWE_ROBOT_USER }}
                  GIT_COMMITTER_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
                  GIT_CREDENTIALS: x-access-token:${{ secrets.ZOWE_ROBOT_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PYPI_ROBOT_TOKEN }}
              with:
                  working-dir: onboarding-enabler-python
                  dry-run: ${{ inputs.dry-run }}
                  new-version: ${{ steps.update-version.outputs.version }}
