# This workflow will release project with Gradle

name: Binary snapshot release

on:
    push:
        branches: [ v2.x.x, v3.x.x ]

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 40

        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - uses: ./.github/actions/setup

            - name: Release with Gradle
              run: ./gradlew clean build publishAllVersions -Pzowe.deploy.username=$ARTIFACTORY_USERNAME -Pzowe.deploy.password=$ARTIFACTORY_PASSWORD -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_USERNAME
              env:
                  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
                  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
                  BUILD_NUMBER: ${{ github.run_number }}
                  BRANCH_NAME: ${{ github.ref_name }}

            - name: Store test results
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                name: ReleaseSnapshotAuto-${{ github.run_number }}
                path: |
                    results/**

            - uses: ./.github/actions/teardown
