name: Image snapshot release

on:
    push:
        branches: [ v2.x.x, v3.x.x ]

jobs:
    build-services:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build services
                run: ./gradlew clean build -x test

            -   uses: ./.github/actions/teardown

    publish-images:
        needs:
            - build-services
        uses: zowe/api-layer/.github/workflows/build-conformant-images.yml@v3.x.x
        with:
            forceNoRelease: true
        secrets:
            registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
            registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
            redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
            redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
            zlinux-host: ${{ secrets.ZLINUX_HOST }}
            zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
            zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
            zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}
