name: Verify that all services can register

on:
    push:
        branches: [ v2.x.x, v3.x.x ]
        paths-ignore:
            - '**.md'
    pull_request:
        branches: [ v2.x.x, v3.x.x ]
        paths-ignore:
            - '**.md'
    workflow_dispatch:

env:
    JOB_ID: ${{ github.run_id }}-${{ github.run_number }}

jobs:
    BuildAndTest:
        runs-on: ubuntu-latest
        timeout-minutes: 35

        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Install BATS to test the shell scripts
                run: |
                    git clone https://github.com/bats-core/bats-core.git
                    cd bats-core && sudo ./install.sh /usr/local

            -   name: Run shell script tests
                run: bats scripts/test/start_test.bats

            -   name: Build with Gradle
                run: >
                    ./gradlew clean build --info --scan

            -   name: Store results
                uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: BuildAndTest-${{ env.JOB_ID }}
                    path: |
                        */build/reports/**

            -   uses: ./.github/actions/teardown

    Register:
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            -   uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}

            -   uses: ./.github/actions/setup

            -   name: Build with Gradle
                run: >
                    ./gradlew clean build -x test -x npmTest -x npmInstall -x npmBuild --info --scan

            -   name: Run startup check for microservices
                run: >
                    ./gradlew runStartUpCheck --info --scan -Denvironment.startServices=true

            -   name: Start OpenTelemetry docker containers
                run: |
                    cd otel
                    chmod -R 777 otel-*
                    docker compose up -d

            -   name: Check OpenTelemetry containers
                run: |
                    echo "Checking OpenTelemetry Golden Tester..."
                    curl -s -v -w "\n" http://localhost:5318/v1/metrics -H "Content-Type: application/json" -d "{}" \
                        --fail \
                        --retry-all-errors \
                        --retry-delay 10 \
                        --retry 3
                    if [ "$?" -eq 0 ]; then
                      echo "OpenTelemetry Golden Tester is ready!"
                    fi

                    echo ""
                    echo "Checking OpenTelemetry Collector..."
                    curl -s -v -w "\n" /dev/null http://localhost:4318/v1/metrics -H "Content-Type: application/json" -d "{}" \
                        --fail \
                        --retry-all-errors \
                        --retry-delay 10 \
                        --retry 3
                    if [ $? -eq 0 ]; then
                      echo "OpenTelemetry Collector is ready!"
                    fi

            -   name: Run startup check for modulith
                run: >
                    ./gradlew runStartUpCheckWithOpenTelemetry --info --scan -Denvironment.startServices=true -Denvironment.modulith=true -Denvironment.config=-modulith

            -   name: Verify OpenTelemetry data with Golden Tester
                if: always()
                run: |
                    echo "Waiting for Golden Validator to finish..."

                    # This blocks until the golden container exits (success or timeout)
                    EXIT_CODE=$(docker wait golden)

                    # Display logs to see the diff if it failed
                    echo "Golden container logs:"
                    docker logs golden 2>&1 | tee otel/otel-golden/container.log

                    echo ""

                    if [ "$EXIT_CODE" -ne 0 ]; then
                      echo "::error::OpenTelemetry data validation failed! See logs above for diff."
                      exit 1
                    fi
                    echo "OpenTelemetry data validation passed!"

            -   name: Stop OpenTelemetry Collector and print logs
                if: always()
                run: |
                    docker stop collector -t 60

                    echo "Collector container logs:"
                    docker logs collector 2>&1 | tee otel/otel-collector/container.log

            -   name: Store results
                uses: actions/upload-artifact@v4
                if: always()
                with:
                    name: Register-${{ env.JOB_ID }}
                    path: |
                        */build/reports/**
                        otel/**

            -   uses: ./.github/actions/teardown
