name: zowe-cli-plugin-deployment

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 40
        permissions:
            contents: write
            issues: write

        steps:
            - name: Checkout
              uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  ref: ${{ github.ref }}

            - name: Use Node.js LTS
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 'lts/*'

            - name: Install Dependencies
              run: |
                 cd zowe-cli-id-federation-plugin
                 npm ci

            - name: Update Dependencies
              uses: zowe-actions/octorelease-script@85d3c773c5027a9edd6ae9d079dca338bdf1f4ee # master
              with:
                  working-dir: zowe-cli-id-federation-plugin
                  script: npmUpdate

              env:
                  GIT_COMMITTER_NAME: ${{ secrets.ZOWE_ROBOT_USER }}
                  GIT_COMMITTER_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}

            - name: Build Source
              run: |
                  cd zowe-cli-id-federation-plugin
                  npm run build
                  npm version ${{ github.event.inputs.scope || env.DEFAULT_SCOPE }}

            -   name: Update npm configuration
                run: |
                    cd zowe-cli-id-federation-plugin
                    if [ -e .npmrc ]; then
                      rm -f .npmrc
                    fi

            - uses: zowe-actions/octorelease@6cf71bdb7ca82117775295e076d63fe7a812f3c8 # v1
              with:
                working-dir: zowe-cli-id-federation-plugin
              env:
                  GIT_COMMITTER_NAME: ${{ secrets.ZOWE_ROBOT_USER }}
                  GIT_COMMITTER_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
                  GIT_CREDENTIALS: x-access-token:${{ secrets.ZOWE_ROBOT_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
                  NPM_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
                  NPM_EMAIL: ${{ secrets.ZOWE_ROBOT_EMAIL }}
